import turtle
turtle=turtle.Turtle()
turtle.speed(7)
turtle.penup()
turtle.goto(-120, 50)

turtle.pendown()

# M
turtle.left(90)
turtle.forward(50)
turtle.right(135)
turtle.forward(35)
turtle.left(90)
turtle.forward(35)
turtle.right(135)
turtle.forward(50)
turtle.penup()
turtle.right(90)
turtle.forward(10)
turtle.goto(-50, 100) 
turtle.pendown()

# I
turtle.left(90)
turtle.forward(50)
turtle.penup()
turtle.backward(50)
turtle.right(90)
turtle.forward(10)
turtle.goto(-30, 50) 
turtle.pendown()

# H
turtle.right(90)
turtle.forward(50)
turtle.backward(25)
turtle.right(90)
turtle.forward(25)
turtle.left(90)
turtle.forward(25)
turtle.right(180)
turtle.forward(50)
turtle.penup()
turtle.goto(15, 50) 
turtle.pendown()

# I
turtle.left(180)
turtle.forward(50)
turtle.penup()
turtle.backward(50)
turtle.right(90)
turtle.forward(10)
turtle.penup()
turtle.goto(30, 50) 
turtle.pendown()

# R
turtle.left(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(5)
turtle.circle(-15,180)
turtle.forward(5)
turtle.left(140)
turtle.forward(30)
turtle.penup()

# D
turtle.goto(-200, -40)
turtle.left(130)
turtle.pendown()
turtle.forward(50)
turtle.right(90)
turtle.circle(-25, 180)
turtle.penup()

# E
turtle.goto(-130, -40)
turtle.pendown()
turtle.forward(30)
turtle.right(90)
turtle.forward(25)
turtle.right(90)
turtle.forward(20)
turtle.backward(20)
turtle.left(90)
turtle.forward(25)
turtle.right(90)
turtle.forward(30)
turtle.penup()

# S
turtle.goto(-115, -40)
turtle.pendown()
turtle.forward(10)
turtle.circle(12.5, 180)
turtle.circle(-12.5, 180)
turtle.forward(10)
turtle.penup()
          
# H
turtle.goto(-75, -40)
turtle.left(90)
turtle.pendown()
turtle.forward(50)
turtle.backward(25)
turtle.right(90)
turtle.forward(25)
turtle.left(90)
turtle.forward(25)
turtle.right(180)
turtle.forward(50)
turtle.penup()

# P
turtle.goto(-30, -40)
turtle.left(180)
turtle.pendown()
turtle.forward(50)
turtle.right(90)
turtle.forward(5)
turtle.circle(-15, 180)
turtle.forward(5)
turtle.penup()

# A 
turtle.goto(0, -40)
turtle.right(110)
turtle.pendown()
turtle.forward(55)
turtle.right(145)
turtle.forward(55)
turtle.penup()
turtle.goto(7, -20)
turtle.left(75)
turtle.pendown()
turtle.forward(20)
turtle.penup()

# N
turtle.goto(45, -40)
turtle.left(90)
turtle.pendown()
turtle.forward(50)
turtle.right(145)
turtle.forward(60)
turtle.left(145)
turtle.forward(50)
turtle.penup()

# D
turtle.goto(95, -40)
turtle.pendown()
turtle.forward(50)
turtle.right(90)
turtle.circle(-25, 180)
turtle.penup()

# E
turtle.goto(165, -40)
turtle.pendown()
turtle.forward(30)
turtle.right(90)
turtle.forward(25)
turtle.right(90)
turtle.forward(20)
turtle.backward(20)
turtle.left(90)
turtle.forward(25)
turtle.right(90)
turtle.forward(30)